FROM docker.io/alpine:3.20 as ksource

RUN ["apk", "add", "linux-virt-dev"]

FROM docker.io/alpine:3.20

COPY --from=ksource /usr/src/linux-headers-*-virt/scripts/sign-file /usr/local/bin/sign-file

ENTRYPOINT ["/usr/local/bin/sign-file"]
