/*
Copyright (c) Advanced Micro Devices, Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the \"License\");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an \"AS IS\" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: filesystem_helper.go
//
// Generated by this command:
//
//	mockgen -source=filesystem_helper.go -package=utils -destination=mock_filesystem_helper.go
//
// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFSHelper is a mock of FSHelper interface.
type MockFSHelper struct {
	ctrl     *gomock.Controller
	recorder *MockFSHelperMockRecorder
}

// MockFSHelperMockRecorder is the mock recorder for MockFSHelper.
type MockFSHelperMockRecorder struct {
	mock *MockFSHelper
}

// NewMockFSHelper creates a new mock instance.
func NewMockFSHelper(ctrl *gomock.Controller) *MockFSHelper {
	mock := &MockFSHelper{ctrl: ctrl}
	mock.recorder = &MockFSHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFSHelper) EXPECT() *MockFSHelperMockRecorder {
	return m.recorder
}

// FileExists mocks base method.
func (m *MockFSHelper) FileExists(root, fileRegex string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", root, fileRegex)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockFSHelperMockRecorder) FileExists(root, fileRegex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockFSHelper)(nil).FileExists), root, fileRegex)
}

// RemoveSrcFilesFromDst mocks base method.
func (m *MockFSHelper) RemoveSrcFilesFromDst(srcDir, dstDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSrcFilesFromDst", srcDir, dstDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSrcFilesFromDst indicates an expected call of RemoveSrcFilesFromDst.
func (mr *MockFSHelperMockRecorder) RemoveSrcFilesFromDst(srcDir, dstDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSrcFilesFromDst", reflect.TypeOf((*MockFSHelper)(nil).RemoveSrcFilesFromDst), srcDir, dstDir)
}
